appType:
  appBaseUrl:
    public: 'http://localhost:PORT or https://app-domain.com'
    admin: 'http://localhost:PORT or https://admin.app-domain.com'

session:
  storage:
    redisUrl: 'redis://foo:bar@awesome.redis.server:6380'
  cookie:
    # This is the secret used to sign the session ID cookie.
    #
    # The secret can be any type of value that is supported by Node.js crypto.createHmac
    # (like a string or a Buffer).
    #
    # IMPORTANT:
    # - Do periodic updates of the secret, while ensuring the previous secret is in the array.
    # - Use a secret that cannot be guessed.
    #
    # Changing the secret value will invalidate all existing sessions. In order to
    # rotate the secret without invalidating sessions, provide an array of secrets,
    # with the new secret as first element of the array, and including previous secrets
    # as the later elements.
    #
    # Note HMAC-256 is used to sign the session ID. For this reason, the secret should
    # contain at least 32 bytes of entropy.
    #
    # Learn more at https://www.npmjs.com/package/express-session.
    # TODO: rotate this automatically
    signIdSecrets: ['...', '...']
  ttl:
    idleMs:
      public: 99999
      admin: 99999
    absoluteMs:
      public: 99999
      admin: 99999
